services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh 
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql  
  
volumes:
  postgres_data:
